# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: quick-check

on:
  push:
    branches: 
    - '**'
  pull_request:
    branches:
    - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --upgrade coverage pytest
        python setup.py develop
    - name: Run tests
      run: |
        coverage run --source=pecos -m pytest --doctest-modules --doctest-glob="*.rst" pecos        
        coverage report --fail-under=70                                        
